# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_process', '0002_auto_20160314_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_sequence', models.IntegerField()),
                ('vote_content', models.CharField(max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_process.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_process.User')),
            ],
        ),
        migrations.CreateModel(
            name='vote_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_sequence', models.IntegerField()),
                ('spy_vote_count', models.IntegerField()),
                ('civilian_vote_count', models.IntegerField()),
                ('which_side_get_point', models.CharField(max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_process.Room')),
            ],
        ),
    ]
