# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guess_word', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='word_content',
        ),
    ]
