# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPhrase', models.CharField(max_length=10)),
                ('secondPhrase', models.CharField(max_length=10)),
                ('phraseId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNum', models.IntegerField()),
                ('userCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhraseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_process.PhraseEntry')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_process.Room')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInRoomIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_process.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_process.User')),
            ],
        ),
    ]
