# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_process', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phraseentry',
            name='phraseId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
    ]
