# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWaitForInitRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_type', models.CharField(max_length=20)),
                ('wait_time', models.DateTimeField(default=datetime.datetime(2016, 3, 11, 15, 53, 33, 901000))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_process.User')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='modifiedTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 11, 15, 53, 33, 898000)),
        ),
    ]
