# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='modifiedTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 15, 17, 35, 7000)),
        ),
        migrations.AlterField(
            model_name='userwaitforinitroom',
            name='wait_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 15, 17, 35, 12000)),
        ),
    ]
