# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_process', '0002_auto_20160309_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='identityDistribution',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
