# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_process', '0002_auto_20160314_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='game_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='game_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='modifiedTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 16, 52, 3, 429000)),
        ),
        migrations.AlterField(
            model_name='userwaitforinitroom',
            name='wait_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 16, 52, 3, 432000)),
        ),
    ]
