# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_process', '0003_room_identitydistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinroomidentity',
            name='aliveOrDead',
            field=models.IntegerField(null=True),
        ),
    ]
